//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisaMetaka.ImaLiKoJaci.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public Song()
        {
            this.Lyrics = new HashSet<Lyrics>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string YoutubeUrl { get; set; }
    
        public virtual ICollection<Lyrics> Lyrics { get; set; }
    }
}
