//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisaMetaka.ImaLiKoJaci.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public string FacebookId { get; set; }
        public System.DateTime JoinedOn { get; set; }
        public int TotalScore { get; set; }
    }
}
